### PR TITLE
feat(formula): align to template formula; add ci tests

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [x] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [x] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [x] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

YES

### Describe the changes you're proposing

Following Intellij blueprint, align to template formula and add CI tests

### Documentation checklist

- [x] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [x] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by noelmcloughlin** [comment]
MacOS trace
```
local:
----------
          ID: webstorm-macos-app-clean-files
    Function: file.absent
        Name: /tmp/jetbrains/webstorm
      Result: True
     Comment: File /tmp/jetbrains/webstorm is not present
     Started: 21:23:04.013598
    Duration: 0.454 ms
     Changes:   
----------
          ID: webstorm-macos-app-clean-files
    Function: file.absent
        Name: /Applications/Webstorm.app
      Result: True
     Comment: File /Applications/Webstorm.app is not present
     Started: 21:23:04.014166
    Duration: 0.291 ms
     Changes:   
----------
          ID: webstorm-config-clean-file-absent
    Function: file.absent
        Name: /tmp/dummy_list_item
      Result: True
     Comment: File /tmp/dummy_list_item is not present
     Started: 21:23:04.014621
    Duration: 0.298 ms
     Changes:   
----------
          ID: webstorm-config-clean-file-absent
    Function: file.absent
        Name: /etc/defaults/webstorm.sh
      Result: True
     Comment: File /etc/defaults/webstorm.sh is not present
     Started: 21:23:04.015073
    Duration: 0.293 ms
     Changes:   
----------
          ID: webstorm-config-clean-file-absent
    Function: file.absent
        Name: /Users/nmcloughlin/Desktop/Webstorm
      Result: True
     Comment: File /Users/nmcloughlin/Desktop/Webstorm is not present
     Started: 21:23:04.015518
    Duration: 0.29 ms
     Changes:   
----------
          ID: webstorm-macos-app-install-curl
    Function: file.directory
        Name: /tmp/jetbrains/webstorm
      Result: True
     Comment: Directory /tmp/jetbrains/webstorm updated
     Started: 21:23:04.015905
    Duration: 5.628 ms
     Changes:   
              ----------
              /tmp/jetbrains/webstorm:
                  New Dir
----------
          ID: webstorm-macos-app-install-curl
    Function: pkg.installed
        Name: curl
      Result: True
     Comment: All specified packages are already installed
     Started: 21:23:08.179264
    Duration: 10686.482 ms
     Changes:   
----------
          ID: webstorm-macos-app-install-curl
    Function: cmd.run
        Name: curl -Lo /tmp/jetbrains/webstorm/webstorm-2020.1 https://download.jetbrains.com/webstorm/WebStorm-2020.1.dmg
      Result: True
     Comment: Command "curl -Lo /tmp/jetbrains/webstorm/webstorm-2020.1 https://download.jetbrains.com/webstorm/WebStorm-2020.1.dmg" run
     Started: 21:23:18.869233
    Duration: 1399739.728 ms
     Changes:   
              ----------
              pid:
                  62815
              retcode:
                  0
              stderr:
                    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                                   Dload  Upload   Total   Spent    Left  Speed
                  
                    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
                    0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
                  100   138  100   138    0     0    157      0 --:--:-- --:--:-- --:--:--   157
                  
                    0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
                    0  317M    0 32199    0     0  15189      0  6:05:52  0:00:02  6:05:50 35422
                    0  317M    0  207k    0     0  67724      0  1:22:03  0:00:03  1:22:00  107k
                    0  317M    0  318k    0     0  77568      0  1:11:38  0:00:04  1:11:34  106k
                    0  317M    0  447k    0     0  79396      0  1:09:59  0:00:05  1:09:54   98k
                    0  317M    0  570k    0     0  94598      0  0:58:44  0:00:06  0:58:38  114k
                    0  317M    0  575k    0     0  78030      0  1:11:13  0:00:07  1:11:06  100k
                    0  317M    0  655k    0     0  82515      0  1:07:20  0:00:08  1:07:12 91782
                    0  317M    0  767k    0     0  85214      0  1:05:12  0:00:09  1:05:03 91642
                    0  317M    0  911k    0     0  92199      0  1:00:16  0:00:10  1:00:06  106k
                    0  317M    0 1038k    0     0  95649      0  0:58:05  0:00:11  0:57:54 96947
                    0  317M    0 1070k    0     0  89793      0  1:01:53  0:00:12  1:01:41  106k
                    0  317M    0 1150k    0     0  89804      0  1:01:52  0:00:13  1:01:39   99k
                    0  317M    0 1214k    0     0  87792      0  1:03:17  0:00:14  1:03:03 92600
                    0  317M    0 1406k    0     0  91968      0  1:00:25  0:00:15  1:00:10 91560

           <<< CUT >>>

                   99  317M   99  317M    0     0   232k      0  0:23:20  0:23:18  0:00:02  139k
                   99  317M   99  317M    0     0   232k      0  0:23:20  0:23:19  0:00:01  195k
                  100  317M  100  317M    0     0   232k      0  0:23:19  0:23:19 --:--:--  250k
              stdout:
----------
          ID: webstorm-macos-app-install-checksum
    Function: module.run
        Name: file.check_hash
      Result: True
     Comment: onlyif condition is false
     Started: 21:46:38.610615
    Duration: 561.854 ms
     Changes:   
----------
          ID: webstorm-macos-app-install-checksum
    Function: file.absent
        Name: /tmp/jetbrains/webstorm/webstorm-2020.1
      Result: True
     Comment: State was not run because onfail req did not change
     Started: 21:46:39.173295
    Duration: 0.004 ms
     Changes:   
----------
          ID: webstorm-macos-app-install-macpackage
    Function: macpackage.installed
        Name: /tmp/jetbrains/webstorm/webstorm-2020.1
      Result: True
     Comment: WebStorm.app installed
     Started: 21:46:39.173529
    Duration: 23903.852 ms
     Changes:   
              ----------
              installed:
                  - WebStorm.app
----------
          ID: webstorm-macos-app-install-macpackage
    Function: file.managed
        Name: /tmp/mac_shortcut.sh
      Result: True
     Comment: File /tmp/mac_shortcut.sh updated
     Started: 21:47:03.077692
    Duration: 37.282 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1,5 +1,5 @@
                   #!/usr/bin/env bash
                   
                  -Source="/Applications/Phpstorm.app"
                  +Source="/Applications/Webstorm.app"
                   Destination="/Users/nmcloughlin/Desktop"
                   /usr/bin/osascript -e "tell application \"Finder\" to make alias file to POSIX file \"$Source\" at POSIX file \"$Destination\""
----------
          ID: webstorm-macos-app-install-macpackage
    Function: cmd.run
        Name: /tmp/mac_shortcut.sh
      Result: True
     Comment: Command "/tmp/mac_shortcut.sh" run
     Started: 21:47:03.115613
    Duration: 2169.46 ms
     Changes:   
              ----------
              pid:
                  65436
              retcode:
                  0
              stderr:
              stdout:
                  alias file WebStorm of folder Desktop of folder nmcloughlin of folder Users of startup disk
----------
          ID: webstorm-config-file-file-managed-environ_file
    Function: file.managed
        Name: /etc/defaults/webstorm.sh
      Result: True
     Comment: File /etc/defaults/webstorm.sh updated
     Started: 21:47:05.285653
    Duration: 1833.599 ms
     Changes:   
              ----------
              diff:
                  New file
              group:
                  nmcloughlin
              mode:
                  0644
              user:
                  nmcloughlin

Summary for local
-------------
Succeeded: 14 (changed=6)
Failed:     0
```

**Comment by myii** [comment]
@noelmcloughlin Merged, I was able to push the extra commit here directly, which makes for a nice change!

**Comment by noelmcloughlin** [comment]
Thanks @myii I'm genuinely unsure what led to the issue on other formula.
I'm always happy to let maintainers update my PR, and I have often fixed
conflicts and merged other peoples PRs too using this github feature.

**Comment by myii** [comment]
> Thanks @myii I'm genuinely unsure what led to the issue on other formula. I'm always happy to let maintainers update my PR, and I have often fixed conflicts and merged other peoples PRs too using this github feature.

@noelmcloughlin I don't think it's anything from your side.  I've noticed some glitches since adding the GitHub Action to the repos, where it mentions something about the risks of sharing secrets -- I think it's unchecking allow edits from there itself.  Let's keep an eye on it; hopefully we can figure out what's causing this to happen.

**Pull request merged**
